"""fixed the get post and user

Revision ID: 182124eaa000
Revises: d6caa57fa395
Create Date: 2025-11-14 00:01:11.977498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182124eaa000'
down_revision: Union[str, Sequence[str], None] = 'd6caa57fa395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
