"""added created at for user

Revision ID: 2e4217ef3692
Revises: 8622893e5101
Create Date: 2025-11-13 22:34:47.355675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4217ef3692'
down_revision: Union[str, Sequence[str], None] = '8622893e5101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
