"""updated models

Revision ID: 421f6317727d
Revises: 10bd69ed66ed
Create Date: 2025-11-21 07:27:07.150962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421f6317727d'
down_revision: Union[str, Sequence[str], None] = '10bd69ed66ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=True))
    op.alter_column('user', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'hashed_password')
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
