"""commented out content

Revision ID: 74b552acec1d
Revises: 195797163820
Create Date: 2025-11-11 00:14:16.941641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b552acec1d'
down_revision: Union[str, Sequence[str], None] = '195797163820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
