"""added created at for user

Revision ID: 8622893e5101
Revises: f6ad5fd46a9d
Create Date: 2025-11-13 22:32:40.966294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8622893e5101'
down_revision: Union[str, Sequence[str], None] = 'f6ad5fd46a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.alter_column('post', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
