"""added content in models

Revision ID: bf05c0cb3c5a
Revises: 74b552acec1d
Create Date: 2025-11-11 00:18:20.317053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf05c0cb3c5a'
down_revision: Union[str, Sequence[str], None] = '74b552acec1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
