"""added password for user

Revision ID: cf434951ad6b
Revises: 182124eaa000
Create Date: 2025-11-17 22:19:14.588870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf434951ad6b'
down_revision: Union[str, Sequence[str], None] = '182124eaa000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('post', 'created_at')
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.alter_column('user', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'password')
    op.add_column('post', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
