"""new commit

Revision ID: f6ad5fd46a9d
Revises: d3d545ac44df
Create Date: 2025-11-13 18:40:37.262866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ad5fd46a9d'
down_revision: Union[str, Sequence[str], None] = 'd3d545ac44df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('post', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
